# Generated by Django 3.2.6 on 2021-09-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_contact',
            field=models.IntegerField(max_length=13),
        ),
    ]
